#!/bin/bash
VERSION="0.8"
if [ "x$1" = "xversion" ]; then
	echo $VERSION
fi
if [ "$1" = "init" ]; then
	if ! /opt/mega/MegaCli64 -adpCount -nolog > /dev/null 2>&1; then
		/opt/mega/MegaCli64 -CfgSave -f /tmp/raid_saved -a0 -nolog
		/opt/mega/MegaCli64 -CfgClr -Force -aALL -nolog 
		enc=`/opt/mega/MegaCli64 -PDList -aALL -nolog|grep -i "Enclosure Device ID"|sed -n 1p|awk -F : '{print $2}'|tr -d " "`
		slots=`/opt/mega/MegaCli64 -PDList -aALL -nolog|grep -i slot|awk -F : '{print $2}'|tr -d " "`
		for i in $slots
		do
			/opt/mega/MegaCli64 -PDMakeGood -PhysDrv [$enc:$i] -Force -aALL -nolog > /dev/null 2>&1
			/opt/mega/MegaCli64 -CfgLdAdd -r0[$enc:$i] WB -a0 -nolog > /dev/null 2>&1
		done
	fi
	if  /opt/cmdline/arcconf GETCONFIG 1 > /dev/null 2>&1 ; then
		yes | /opt/cmdline/arcconf DELETE 1 JBOD ALL  > /dev/null
		yes | /opt/cmdline/arcconf DELETE 1 LOGICALDRIVE ALL > /dev/null
		slot_num=`/opt/cmdline/arcconf GETCONFIG 1 PD|grep -i Channel,Device|wc -l`
		slots=`/opt/cmdline/arcconf GETCONFIG 1 PD|grep -i Channel,Device|sed ${slot_num}d|awk -F [:\(] '{print $4}'|tr -d " " `
		for slot in $slots
		do
			/opt/cmdline/arcconf CREATE 1 JBOD $slot
		done
		
	fi
elif [ "$1" = "restore" ];then

	if ! /opt/mega/MegaCli64 -adpCount -nolog> /dev/null 2>&1; then
		if [ -e /tmp/raid_saved ] ;then
			/opt/mega/MegaCli64 -CfgClr -Force -aALL -nolog
			/opt/mega/MegaCli64 -CfgRestore -f /tmp/raid_saved -a0 -nolog
		else 
			return -1
		fi
	fi
	if  /opt/cmdline/arcconf GETCONFIG 1 > /dev/null 2>&1 ; then
		yes | /opt/cmdline/arcconf SETCONFIG 1 DEFAULT
		
	fi

fi
