#!/bin/sh
VERSION="1.1"
if [ "x$1" = "xversion" ];then
	echo $VERSION
	exit 0
fi
eths=`ls /sys/class/net | grep -v lo`
if [ ! -d /tmp/old ];then
	mkdir /tmp/old/
fi

for eth in $eths
do
	info=`ifconfig $eth|grep inet|grep -v inet6`
	echo $info > /tmp/old/$eth
done

route=`route -n|grep ^0.0.0.0|awk '{print $2}'`
if [ "x$route" != "x" ];then
	echo $route > /tmp/route
fi

i=1
for eth in $eths
do
	ifconfig $eth 192.13.$i.3 netmask 255.255.255.0
	i=$(($i+1))
done

sleep 3

ping -W 3 -c 2 192.13.1.1 > /dev/null 2>&1
if [ $? -ne 0 ] ; then
	i=1
	for eth in $eths
	do
		ifconfig $eth 192.13.$i.1 netmask 255.255.255.0
		iperf -s -p 501$i > /dev/null 2>&1 &
		i=$(($i+1))
	done
else
	i=1
	for eth in $eths 
	do
		ifconfig $eth 192.13.$i.2 netmask 255.255.255.0
		iperf -s -p 502$i > /dev/null 2>&1 &
		i=$(($i+1))
	done	
fi

rm -rf /run/lock/jw-aging.lock > /dev/null 2>&1
while true
do
	str=""
	str=`nc -l -p 21700`
	if [ x"$str" = "x1" ]; then
		touch /run/lock/jw-aging.lock
		echo `date +"%s"` > /run/lock/jw-aging.lock
	elif [ x"$str" = "x2" ]; then
		rm -rf /run/lock/jw-aging.lock
	fi 
done
